export type GlossaryEntry = {
  中文名稱: string;
  englishField: string;
  定義: string;
  計算方式: string;
  如何解讀: string;
  注意事項: string;
  更新頻率: string;
};

const entry = (
  中文名稱: string, englishField: string, 定義: string, 計算方式 = "由掃描器依版本化規格計算或由來源資料保留。",
  如何解讀 = "數值用來描述當日部位活動結構，必須連同資料完整度閱讀。",
  注意事項 = "Phase 2A 僅供研究，不是交易建議。", 更新頻率 = "每次手動掃描",
): GlossaryEntry => ({ 中文名稱, englishField, 定義, 計算方式, 如何解讀, 注意事項, 更新頻率 });

export const fieldGlossary = {
  same_day_activity_score: entry("同日活動分數", "Same-Day Activity Score", "非 0DTE 以當期活動相對真正可比的非零 DTE peers 評分；DTE 0 則以同 ticker 前 20 個有效 0DTE sessions 獨立校準。", "非 0DTE 使用 Volume Share（60）與 Comparable Neighbor（40）；0DTE 使用 robust deviation（70）與 historical percentile（30）。", "只描述 expiry 層級的最新成交活動異常度。", "0DTE 未滿 20 個 prior sessions 時為 unavailable；raw neighbor 對 0DTE 權重為零。"),
  persistent_positioning_score: entry("持續部位分數", "Persistent Positioning Score", "跨多個有效 OI observation sessions 是否持續形成或下降。", "各自計算 3／5／10 個有效 observation windows，採可用視窗最高分。", "分數描述 OI positioning 的持續性。", "D 是有效 OI observation session，不是日曆日；少於三筆時 unavailable。", "每日 vendor OI observation date"),
  discovery_score: entry("歷史探索分數", "Legacy Discovery Score (v1.2)", "僅保留於 v1.2 歷史結果的版本化欄位；v1.3 主流程不使用 universal Discovery Score。", "依 signal_spec_v1.2_phase2a 原規格重現。", "只用於歷史診斷。", "v1.3 不以此欄選擇、平均或排序三條路由。"),
  discovery_source: entry("探索來源", "Discovery Source", "SAME_DAY、PERSISTENT、BOTH 或 NONE；BOTH 僅在 secondary score 至少 40 且實際貢獻 bonus 時使用。", "依 primary 與 meaningful secondary evidence 決定。", "說明哪一條獨立證據真正貢獻 Discovery。"),
  discovery_evidence_breadth: entry("證據廣度", "Evidence Breadth", "顯示零、一或兩條獨立 discovery evidence tracks 有意義地貢獻。", "0=沒有可用 Discovery；1=一條 primary；2=兩條且 secondary 至少 40。", "這是證據覆蓋資訊，不是額外分數。"),
  zero_dte_baseline: entry("0DTE 基準", "0DTE Baseline", "使用同 ticker 前 20 個有效 DTE-0 observations，且排除 current observation。", "依有效 observation sessions 計數，不按日曆日。", "未滿 20 筆是 cold start，不是市場訊號。"),
  rolling_mean_0dte: entry("0DTE 滾動平均", "Rolling Mean", "前 20 個有效 0DTE Volume Share 的直觀描述性平均。", "sum(prior 20 shares) / 20。", "方便理解典型水準，但不直接作 robust scoring center。"),
  rolling_median_mad_0dte: entry("0DTE 中位數與 MAD", "Rolling Median + MAD", "以中位數與 median absolute deviation 建立抗極端值的 0DTE anomaly baseline。", "robust deviation = (current − median) / (1.4826 × MAD)。", "MAD 不可用時不除以零，僅保留 fixed-scale percentile evidence。"),
  historical_percentile_0dte: entry("0DTE 歷史百分位", "Historical Percentile", "目前 0DTE Volume Share 在同 ticker 前 20 個有效 observations 中的 empirical rank。", "prior values <= current 的筆數除以 20；ties 計入 current rank。", "只使用 prior observations，不含本次 current value。"),
  cold_start: entry("冷啟動", "Cold Start", "歷史 observations 不足以計算 calibrated score。", "0DTE 少於 20 prior sessions 或 Persistent 少於規格要求時標示。", "Cold start 是資料覆蓋狀態，不是市場訊號，也不應顯示為零。"),
  oi_share: entry("OI 佔比", "OI Share", "某 expiry 的 OI 佔該 ticker 指定 0–180 DTE 範圍總 OI 的比例。", "expiry_total_oi / ticker_total_oi_in_scope。", "描述目前 OI surface 的集中程度。", "分母來自完整的 oi_per_expiry daily surface，不使用 ranked OI-change subset。", "每日 vendor OI observation date"),
  oi_share_change: entry("OI 佔比變化", "OI Share Change (pp)", "該 expiry 在整體 OI surface 中的重要性增加或下降多少 percentage points。", "current OI Share − historical OI Share；例如 8%→24% 為 +16pp。", "正值表示相對集中度增加。", "不是相對百分比成長；缺少指定 observation window 時 unavailable。", "3／5／10 個有效 OI observation sessions"),
  history_coverage: entry("歷史覆蓋", "History Coverage", "有效 OI observation 數量所對應的信心級別。", "<3 INSUFFICIENT；3–4 LOW；5–9 MEDIUM；10+ FULL。"),
  contract_structure_score: entry("合約部位結構分數", "Contract Positioning Structure Score", "衡量某張 option 在目前 expiry OI strike structure 中有多突出；不是當天成交異常分數。", "同側 expiry OI concentration（40）＋鄰近 strike OI anomaly（30）＋ liquidity（15）＋ delta（15）。", "適合比較同一 expiry、同一 right 的結構集中度。", "不使用 contract volume、premium、historical volume 或 intraday burst。", "最新完整 Daily OI Archive"),
  contract_persistent_score: entry("合約持續部位分數", "Contract Persistent Positioning Score", "衡量該 contract 的 OI 是否跨多個有效 observation sessions 持續累積或下降。", "OI growth、相對同側 expiry OI 的 absolute build share、directional persistence；取 3／5／10 視窗最高分。", "描述 persistent positioning，不推論買賣方向。", "第一次觀察不假設 prior OI 為零。", "每日 vendor OI observation date"),
  oi_change_radar_status: entry("OI 變動雷達", "OI Change Radar", "Nightwatch ranked changed-contract subset 的額外證據；未出現在 Radar 不代表沒有 OI 變動。", "只標示 OBSERVED／NOT_OBSERVED 並保留 subset 證據。", "可補充 ΔOI、premium、rank。", "不得當作完整 OI universe 或 OI Share 分母。"),
  ticker_call_put_volume: entry("Ticker Call／Put 成交量", "Ticker Call/Put Volume", "整個 ticker 的當日 Call/Put activity；不能直接歸因到某一 expiry。", "來自 options.options_volume ticker-day payload。"),
  intraday_activity_v11: entry("盤中活動", "Intraday Activity", "Phase 2A v1.2 不參與 scoring。", "Weight = 0；completed payload semantics 驗證前為 research-only。", "目前顯示 INTRADAY_PROFILE_UNAVAILABLE。"),
  radar_material_event: entry("Radar 重大事件", "Radar Material Event", "Nightwatch vendor-ranked 合約證據同時達到當次已版本化 Premium 與絕對 OI 變化門檻。", "只使用事件保存的 effective threshold profile 評估。", "是需要深入研究的合約活動證據。", "不是 unusual single order、block、sweep、whale 或機構活動證明；未出現在 Radar 也不是負面證據。", "每日 OI Change Radar"),
  persistent_positioning: entry("持續部位", "Persistent Positioning", "由掃描器自己的完整 Daily OI Archive 跨多個有效 observation sessions 推導的合約或到期日 OI 行為。", "保留 3／5／10 session 視窗及既有 v1.2 公式。", "可描述持續 build 或 decline，不依賴 vendor-ranked Radar subset。", "build 不自動看多、decline 不自動看空；少於三筆時為 NULL 並顯示收集進度。", "每日 vendor OI observation date"),
  radar_premium: entry("Radar 權利金", "Premium", "供應商回傳之該合約彙總活動 Premium。", "直接保留 premium_usd；另可描述 premium / trades。", "用來描述彙總合約活動規模。", "不證明存在一筆同等金額的單一委託。", "每日 OI Change Radar"),
  delta_oi: entry("未平倉量變化", "ΔOI", "供應商目前與前一個 OI observation 的絕對差。", "oi − prev_oi；v1.3 eligibility 比較 abs(ΔOI) 與該版本門檻。", "正值是 OI 增加，負值是 OI 減少。", "正 ΔOI 不自動代表看多，負 ΔOI 不自動代表看空。", "每日 OI Change Radar"),
  oi_change_percent: entry("未平倉量相對變化", "OI Change %", "相對於 previous OI 的變化比例。", "由 Nightwatch oi_change 原值保留。", "提供小基數風險的描述背景。", "小 previous OI 可機械性放大百分比；v1.3 不以此欄獨立觸發 Radar eligibility。", "每日 OI Change Radar"),
  expiry_activity: entry("到期日活動", "Expiry Activity", "目前 expiry 層級的 activity concentration，是 v1.3 第三條獨立 Discovery route。", "沿用 v1.2 Same-Day Activity 規格。", "回答目前活動是否集中於此 expiry。", "不與 Radar 或 Persistent 分數平均。", "每次活動快照或互動掃描"),
  monthly_opex: entry("月度 OPEX", "Monthly OPEX", "依標準每月第三個星期五曆法推定的顯示背景。", "Calendar inference；source 明確標為 INFERRED。", "協助理解 monthly expiry 背景。", "v1.3 score weight = 0，沒有 OPEX bonus 或 penalty。"),
  score_basis: entry("分數基礎", "Score Basis", "說明非 0DTE Same-Day 分數主要來自 Volume Share Points、Neighbor Points 或兩者平衡。", "VS > Neighbor + 10 為 VOLUME_SHARE_DOMINATED；Neighbor > VS + 10 為 NEIGHBOR_DOMINATED；其餘 BALANCED。", "只增加可解釋性。", "分類 score weight = 0，不改變原數值分數。"),
  trigger_sources: entry("觸發來源", "Trigger Sources", "列出研究候選是經由 RADAR_EVENT、CONTRACT_PERSISTENCE、EXPIRY_PERSISTENCE、EXPIRY_ACTIVITY 或 STRUCTURAL_COLD_START 進入。", "各路由獨立判斷，去重後附加到同一 Deep Dive。", "可同時存在多個理由。", "不合併成 universal conviction score。"),
  radar_archive_match: entry("Radar 封存匹配", "Radar Archive Match", "oi_change option symbol 與已封存 contract_symbol 的 exact string equality 結果。", "只允許 literal exact join。", "EXACT 可顯示 expiry/right/strike 與 archive 結構；UNJOINED 仍保留事件。", "不解析 OSI 來補造 metadata；incomplete chain 不計 complete-universe metrics。"),
  radar_threshold_profile: entry("Radar 門檻設定檔", "Radar Threshold Profile", "每次 Radar 評估使用的 runtime profile ID、不可變版本、設定雜湊與有效門檻快照。", "門檻由 server-side runtime configuration 注入評估函式。", "讓歷史 eligibility 可依當時版本重現。", "變更 active threshold 必須使用新版本；不會回寫歷史結果。"),
  archive_vendor_oi_date: entry("Archive OI 日期", "Archive Vendor OI Date", "目前結果所重用的 Nightwatch vendor OI observation date。", "由 vendor date/as_of 決定，不以 job 執行日製造日期。", "顯示 Daily OI Archive freshness。", "同 vendor date 重跑會 skip/reuse，不新增重複 snapshot。"),
  ticker: entry("股票代號", "Ticker", "美股標的代號。", "固定 MAG7 清單。"),
  dte: entry("距到期日天數", "DTE", "以紐約市場日期計算的日曆天數。", "到期日 − America/New_York 市場日期。"),
  bucket: entry("到期區間", "Bucket", "依 DTE 分組的期限區間。", "0–7、8–30、31–90、91–180 日。"),
  bucket_at_detection: entry("偵測時到期區間", "bucket_at_detection", "偵測當下固定保存的期限分組。", "依 dte_at_detection 計算。", "歷史欄位不可覆寫。"),
  current_bucket: entry("目前到期區間", "current_bucket", "隨市場日期動態重算的期限分組。"),
  volume: entry("成交量", "Volume", "當日合約成交張數。"),
  open_interest: entry("未平倉量", "Open Interest / OI", "最近可得結算未平倉張數。", "供應商回傳。", "OI 有結算延遲。"),
  volume_oi_ratio: entry("成交量／未平倉量", "Volume/OI", "成交量相對既有 OI 的比例。", "today_volume / max(previous_oi, 1)。", "高比率不證明是新開倉；低 OI 也不會自動使異動無效。"),
  oi_status: entry("OI 確認狀態", "OI Status", "隔日 OI 證據的確認狀態。", "僅 PENDING、CONFIRMED、NOT_CONFIRMED、INCONCLUSIVE。", "Day-0 可能維持待確認。", "結算資料更新後"),
  estimated_premium: entry("估算權利金", "Estimated Premium", "以最佳可得價格代理估算的成交名目金額。", "volume × 100 × price_proxy。", "僅為規模估計。", "可能不等於實際成交權利金。"),
  premium_estimation_quality: entry("權利金估算品質", "Premium Estimation Quality", "標示 VWAP、供應商彙總、Last 或 Midpoint 等代理方法。"),
  bid: entry("買價", "Bid", "最佳可得買方報價。"),
  ask: entry("賣價", "Ask", "最佳可得賣方報價。"),
  mid: entry("中間價", "Mid", "有效 Bid 與 Ask 的中點。", "(bid + ask) / 2。"),
  spread_pct: entry("價差百分比", "Spread %", "買賣價差相對中間價。", "(ask − bid) / mid。", "越低通常代表流動性越好。", "超過 50% 會硬性排除。"),
  delta: entry("Delta", "Delta", "供應商可得的選擇權 Delta。", "不自行推估。"),
  low_oi_base: entry("低 OI 基準", "LOW_OI_BASE", "previous_oi < 100 的風險旗標。", "布林旗標。", "提醒比例可能被小分母放大。", "不會自動排除異動。"),
  lotto_risk: entry("彩券型風險", "LOTTO_RISK", "abs(delta) < 0.10 的風險旗標。"),
  history_insufficient: entry("歷史不足", "HISTORY_INSUFFICIENT", "有效歷史觀測少於 10 筆。", "該分項不計入可用權重，而不是記零分。"),
  zero_dte: entry("零日到期", "ZERO_DTE", "DTE = 0 的額外風險旗標。"),
  intraday_burst: entry("盤中爆量", "Intraday Burst", "最強五分鐘量相對穩健盤中基準。", "max rolling 5m volume / robust baseline。"),
  contract_anomaly_score: entry("合約異常分數", "Contract Anomaly Score", "活動、權利金、歷史、盤中、流動性與價內外程度的可用分項正規化分數。", "earned / available maximum × 100。", "65 分且權重至少 60 才是 CONTRACT_CANDIDATE。"),
  score_basis_weight: entry("分數基礎權重", "Score Basis Weight", "實際可用分項的最高總權重。", "加總可用分項滿分。", "分數高但基礎權重低時可信度有限。"),
  call_volume: entry("Call 成交量", "Call Volume", "指定到期日的 Call 成交張數。", undefined, undefined, "大額 Call 不自動代表看多。"),
  put_volume: entry("Put 成交量", "Put Volume", "指定到期日的 Put 成交張數。", undefined, undefined, "大額 Put 不自動代表看空。"),
  call_oi: entry("Call 未平倉量", "Call OI", "指定到期日的 Call OI。"),
  put_oi: entry("Put 未平倉量", "Put OI", "指定到期日的 Put OI。"),
  volume_skew: entry("成交量偏斜", "Volume Skew", "Call 與 Put 成交量的對稱差。", "(call_volume − put_volume) / total_volume。", "正負描述活動側別，不代表投資人方向。"),
  oi_skew: entry("OI 偏斜", "OI Skew", "Call 與 Put OI 的對稱差。", "(call_oi − put_oi) / total_oi。"),
  expiry_volume_share: entry("到期日成交量占比", "Expiry Volume Share", "該到期日占標的 0–180 DTE 總成交量的比例。"),
  expiry_oi_share: entry("到期日 OI 占比", "Expiry OI Share", "該到期日占標的 0–180 DTE 總 OI 的比例。"),
  neighbor_ratio: entry("鄰近到期日比率", "Neighbor Ratio", "目前到期日 OI 相對同類鄰近到期日中位數。", "current OI / median comparable OI。", "同類鄰居不足時為 unavailable。"),
  expiry_anomaly_score: entry("到期日異常分數", "Expiry Anomaly Score", "OI、鄰近異常、成交量、偏斜與權利金集中度的正規化分數。"),
  cluster_range: entry("群集履約價範圍", "Cluster Range", "同側候選合約群集的最小至最大履約價。"),
  cluster_volume: entry("群集成交量", "Cluster Volume", "群集內合約成交量總和。"),
  cluster_premium: entry("群集估算權利金", "Cluster Premium", "群集內可估算權利金總和。"),
  cluster_premium_share: entry("群集權利金占比", "Cluster Premium Share", "群集占同到期同側估算權利金的比例。"),
  cluster_volume_share: entry("群集成交量占比", "Cluster Volume Share", "群集占同到期同側成交量的比例。"),
  positioning_center: entry("部位中心", "Premium-Weighted Strike / Positioning Center", "依估算權利金加權的群集履約價中心。", "sum(strike × premium) / sum(premium)。", "僅描述集中位置。", "不是價格目標。"),
  cluster_score: entry("群集分數", "Cluster Score", "合約強度、集中度、連貫性與流動性的正規化分數。"),
  cluster_shape: entry("群集形狀", "Cluster Shape", "TIGHT_CLUSTER、BROAD_CLUSTER 或 LADDER 的決定性形狀分類。"),
  call_dominant: entry("Call 活動主導", "CALL_DOMINANT", "有效 Call 結構強於 Put 結構。", undefined, undefined, "不等同看多。"),
  put_dominant: entry("Put 活動主導", "PUT_DOMINANT", "有效 Put 結構強於 Call 結構。", undefined, undefined, "不等同看空。"),
  two_sided: entry("雙側活動", "TWO_SIDED", "Call 與 Put 都有有效結構。"),
  no_strong_structure: entry("無強結構", "NO_STRONG_STRUCTURE", "尚未形成符合規格的有效群集。"),
  provisional_candidate: entry("暫定部位候選", "PROVISIONAL_POSITIONING_CANDIDATE", "有效群集配合候選到期日的 Day-0 狀態。", undefined, undefined, "不是交易建議，也不是最終 Trade Candidate。"),
  pending: entry("待確認", "PENDING", "等待結算後 OI 證據。"),
  confirmed: entry("已確認", "CONFIRMED", "後續 OI 證據支持部位增加。"),
  not_confirmed: entry("未確認", "NOT_CONFIRMED", "後續 OI 證據未支持部位增加。"),
  inconclusive: entry("無法判定", "INCONCLUSIVE", "資料不足以完成 OI 確認。"),
  scan_status: entry("掃描狀態", "Scan Status", "COMPLETE、PARTIAL、PARTIAL_BUDGET_LIMIT、DATA_PENDING 或 FAILED。"),
  api_consumed_units: entry("API 已消耗單位", "API Consumed Units", "本次掃描中成功 200 的付費資料請求數。"),
  network_attempts: entry("網路嘗試次數", "Network Attempts", "本次掃描實際對 Nightwatch 發出的 HTTP 嘗試數。"),
  strongest_bucket: entry("最強到期區間", "Strongest Bucket", "標的最高分結果所在 DTE bucket。"),
  strongest_expiry: entry("最強到期日", "Strongest Expiry", "標的最高異常分數所在到期日。"),
  strongest_call_cluster: entry("最強 Call 群集", "Strongest Call Cluster", "最高分 Call 履約價群集。"),
  strongest_put_cluster: entry("最強 Put 群集", "Strongest Put Cluster", "最高分 Put 履約價群集。"),
  call_cluster_score: entry("Call 群集分數", "Call Cluster Score", "最強 Call 群集的分數。"),
  put_cluster_score: entry("Put 群集分數", "Put Cluster Score", "最強 Put 群集的分數。"),
  positioning_structure: entry("部位活動結構", "Positioning Structure", "Phase 2A 的側別結構標籤。", undefined, undefined, "描述活動，不是方向或買賣建議。"),
  valid_regular_observation: entry("有效正常交易時段觀測", "Valid Regular-Session Observation", "只有同一交易日期恰好一筆供應商標記為 regular 的資料，才進入每日歷史序列。", "缺少或重複 regular 的日期均略過，不以盤前、盤後或插值取代。", "日曆有缺口時，其餘有效觀測仍可使用。", "窗口以有效交易時段觀測數計算，不是日曆天數。"),
  historical_gap: entry("歷史缺口", "Historical Gap", "沒有唯一且明確 regular-session 觀測的交易日期。", "缺少 regular 或同日多筆 regular 均列為 gap 並保留日期。", "用來判讀價格歷史覆蓋品質。", "gap 不會自動使其餘價格歷史失效。"),
  latest_regular_close: entry("最新正常交易時段收盤", "Latest Valid Regular Close", "正規化每日序列中最新的有效 regular 收盤價。", "與 Current Stock State 分開保存及顯示時間。", "供報酬、SMA、趨勢等歷史計算使用。", "Current Stock State 可能來自盤前、盤中或盤後，不會被插入每日歷史序列。"),
  regular_session_returns: entry("有效交易時段報酬", "1D / 5D / 20D Return", "以最新有效 regular 收盤除以往前 N 個有效觀測的收盤再減一。", "C0 / C[-N] − 1；20D 指二十個有效交易時段觀測，不是二十個日曆日。", "描述歷史收盤變化。", "需要 N+1 筆有效觀測，資料不足時該欄位為 NULL。"),
  sma_20_50: entry("二十／五十期移動平均", "SMA20 / SMA50", "最近二十／五十筆有效 regular-session 收盤的算術平均。", "sum(latest N valid closes) / N。", "描述最新 regular 收盤相對歷史均值的位置。", "OHLC split-adjustment semantics 尚未確認。"),
  price_adjustment_caveat: entry("價格調整限制", "Adjustment Caveat", "Nightwatch OHLC 是否經拆股調整尚未確認。", "不自行假設或製造公司行動調整。", "是研究資料限制，不會單獨令其他有效技術值變成 NULL。", "跨拆股期間使用歷史價格時必須保留此限制。"),
  price_trend: entry("價格趨勢", "Price Trend", "以最新有效 regular 收盤、SMA20 與 SMA50 關係形成的描述性狀態。", "latest regular close > SMA20 > SMA50 為 UPTREND；latest regular close < SMA20 < SMA50 為 DOWNTREND；其餘 MIXED。", "用來描述近期價格結構。", "不是價格預測；不使用 Current Stock State，缺少必要歷史時為 UNKNOWN。"),
  atr_14: entry("十四期平均真實波幅", "ATR14", "最近十四筆有效 regular-session True Range 的算術平均。", "True Range 為 high-low、|high-prev close|、|low-prev close| 的最大值；需要十五筆有效觀測。", "作為近期已實現價格波動尺度。", "不採 Wilder smoothing；OHLC split-adjustment semantics 尚未確認。"),
  strike_distance_atr: entry("履約價 ATR 距離", "Strike Distance ATR", "合約履約價距目前股票價格多少個 ATR 單位。", "(strike − current stock-state price) / ATR14。", "只描述距離與尺度。", "正負不代表原始選擇權部位方向。"),
  iv_rank_phase2b: entry("隱含波動率排名", "IV Rank", "供應商提供的一年期、ticker-level 0–100 IV Rank。", "直接保留供應商數值，不從合約 IV 推導。", "描述 ticker IV 在一年範圍中的相對位置。", "不是該合約自身 IV；Phase 2B v1 不建立 LOW／MID／HIGH。"),
  term_structure_phase2b: entry("波動率期限結構", "IV Term Structure", "各選擇權到期日的供應商隱含波動率節點。", "先做候選到期日 exact match，再顯示較短與較長的最近 DTE 節點。", "用來透明比較不同到期日 IV。", "不插值，也不建立 CONTANGO／BACKWARDATION 分類。"),
  implied_move_phase2b: entry("隱含波動幅度", "Implied Move", "供應商回傳之特定到期日預期幅度背景。", "直接顯示 implied_move_usd 與 implied_move_pct。", "只表示幅度背景。", "不代表上漲或下跌預測。"),
  dealer_heatmap_phase2b: entry("Dealer 熱圖", "Dealer Heatmap", "供應商衍生的多到期日、多履約價 dealer-GEX surface。", "保留實際回傳 cells、row stacks、狀態與時間。", "提供候選周圍 dealer/GEX 結構背景。", "缺失 sparse cells 不得補零；不稱為支撐或壓力。"),
  candidate_gex_cell: entry("候選 GEX 儲存格", "Candidate GEX Cell", "只有同一筆 Heatmap cell 同時精確符合候選 expiration 與 strike 才成立。", "expiration exact equality 且 strike numeric equality。", "EXACT_MATCH 才顯示 net/call/put GEX。", "只在 axes 出現並不構成候選 cell；缺失保持 NULL。"),
  row_stack_phase2b: entry("履約價列堆疊", "Row Stack", "Heatmap 對某履約價的跨到期日列聚合與供應商排名。", "直接保留 row_net_wall_gex_usd、row_abs_wall_gex_usd 與 vendor rank。", "是 ticker-wide、多到期日履約價背景。", "與候選 expiration×strike cell 不同。"),
  degraded_phase2b: entry("降級資料", "Degraded", "供應商有回傳資料，但標示其狀態或完整性降低／不確定。", "保留資料並將 quality 標為 AVAILABLE_DEGRADED。", "仍可研究已回傳證據。", "不得推論未回傳 cell，也不計算需要完整 surface 的集中度。"),
  dealer_unavailable_phase2b: entry("Dealer/GEX 資料不可用", "Dealer/GEX Unavailable", "本次評估沒有可用的 Heatmap surface。", "candidate cell 與 row stack 狀態分別為 UNAVAILABLE 與 ROW_UNAVAILABLE，所有 GEX 數值保持 NULL。", "候選與其他 Phase 2B context 仍然保留。", "不可顯示為零，也不可等同於 usable surface 中的 NOT_PRESENT。"),
  direction_unresolved: entry("方向未解析", "Direction Unresolved", "現有證據無法確立經濟發起部位是 long、short、spread 或 hedge。", "Phase 2B v1 固定保留 UNRESOLVED。", "將 positioning significance 與 directional interpretation 分離。", "Call、正 ΔOI、大 Premium、價格或 GEX 正負都不能單獨解決方向。"),
  last_scan: entry("最近掃描", "Last Scan", "此列結果所屬掃描的完成或開始時間。"),
} satisfies Record<string, GlossaryEntry>;

export type GlossaryKey = keyof typeof fieldGlossary;

export const visibleAnalyticalColumns = [
  "ticker", "strongest_bucket", "strongest_expiry", "dte", "same_day_activity_score",
  "persistent_positioning_score", "discovery_score", "discovery_source",
  "discovery_evidence_breadth",
  "oi_share", "oi_share_change", "oi_skew", "history_coverage",
  "contract_structure_score", "contract_persistent_score", "oi_change_radar_status",
  "call_cluster_score", "put_cluster_score", "archive_vendor_oi_date", "last_scan",
] as const satisfies readonly GlossaryKey[];
